[package]
name = "metadata"
version = "0.1.0"
authors = ["Tarik Kaced <tarik.kaced@proton.me>"]
license = "Apache-2.0"
license-file = "LICENSE"
keywords = ["metadata", "carbonable"]

[[target.starknet-contract]]
sierra = true
casm = true
name = "compiled"

[dependencies]
starknet = ">=2.0.0"

[cairo]
sierra-replace-ids = true
