[package]
name = "metadata"
version = "0.1.0"
authors = ["Tarik Kaced <tarik.kaced@proton.me>"]

[[target.starknet-contract]]
# Enable Sierra codegen.
sierra = true
# Enable CASM codegen.
casm = true
name = "compiled"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = "2.0.0"
