[package]
name = "metadata"
version = "0.1.0"
authors = ["Tarik Kaced <tarik.kaced@proton.me>"]
license = "Apache-2.0"
license-file = "LICENSE"
keywords = ["metadata", "carbonable"]
homepage = "https://github.com/carbonable/metadata"

[[target.starknet-contract]]
sierra = true
casm = true
name = "compiled"

[dependencies]
starknet = ">=2.0.1"

cairo_json = { git = "https://github.com/tekkac/cairo-json.git" }

[cairo]
sierra-replace-ids = true

[scripts]
all = "scarb build && scarb test"
